/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

/**
 *
 * @author Triblex95
 */
public class CPUPanel extends javax.swing.JPanel {

    OrderSystemPanel ejer;
    int categoryNumber = 0;
    
    /**
     * Creates new form CPUPanel
     */
    public CPUPanel() {
        initComponents();

        cpu1.setText(OrderSystem.Phones.get(0).name);
        cpuPrice1.setText(Integer.toString(OrderSystem.Phones.get(0).price));

        cpu2.setText(OrderSystem.Phones.get(1).name);
        cpuPrice2.setText(Integer.toString(OrderSystem.Phones.get(1).price));

        cpu3.setText(OrderSystem.Phones.get(2).name);
        cpuPrice3.setText(Integer.toString(OrderSystem.Phones.get(2).price));

        cpu4.setVisible(false);
        cpu5.setVisible(false);
        cpu6.setVisible(false);
        cpu7.setVisible(false);
        cpu8.setVisible(false);

        /*
        
        cpu2.setText(osc.CPUs.get(1).name);
        cpuPrice2.setText(Integer.toString(osc.CPUs.get(1).price));
        cpu3.setText(osc.CPUs.get(2).name);
        cpuPrice3.setText(Integer.toString(osc.CPUs.get(2).price));
        cpu4.setText(osc.CPUs.get(3).name);
        cpuPrice4.setText(Integer.toString(osc.CPUs.get(3).price));
        cpu5.setText(osc.CPUs.get(4).name);
        cpuPrice5.setText(Integer.toString(osc.CPUs.get(4).price));
        cpu6.setText(osc.CPUs.get(5).name);
        cpuPrice6.setText(Integer.toString(osc.CPUs.get(5).price));
        cpu7.setText(osc.CPUs.get(6).name);
        cpuPrice7.setText(Integer.toString(osc.CPUs.get(6).price));
        cpu8.setText(osc.CPUs.get(7).name);
        cpuPrice8.setText(Integer.toString(osc.CPUs.get(7).price));
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpu1 = new javax.swing.JLabel();
        cpuCombo1 = new javax.swing.JComboBox<>();
        cpuPrice1 = new javax.swing.JLabel();
        addCpu1 = new javax.swing.JButton();
        cpu2 = new javax.swing.JLabel();
        cpuCombo2 = new javax.swing.JComboBox<>();
        cpuPrice2 = new javax.swing.JLabel();
        addCpu2 = new javax.swing.JButton();
        cpuPrice3 = new javax.swing.JLabel();
        addCpu3 = new javax.swing.JButton();
        cpu3 = new javax.swing.JLabel();
        cpuCombo3 = new javax.swing.JComboBox<>();
        cpu4 = new javax.swing.JLabel();
        addCpu4 = new javax.swing.JButton();
        cpuCombo4 = new javax.swing.JComboBox<>();
        cpuPrice4 = new javax.swing.JLabel();
        cpu5 = new javax.swing.JLabel();
        addCpu5 = new javax.swing.JButton();
        cpuCombo5 = new javax.swing.JComboBox<>();
        cpuPrice5 = new javax.swing.JLabel();
        cpu6 = new javax.swing.JLabel();
        addCpu6 = new javax.swing.JButton();
        cpuPrice6 = new javax.swing.JLabel();
        cpuCombo6 = new javax.swing.JComboBox<>();
        cpu7 = new javax.swing.JLabel();
        cpuPrice7 = new javax.swing.JLabel();
        cpuCombo7 = new javax.swing.JComboBox<>();
        addCpu7 = new javax.swing.JButton();
        cpuCombo8 = new javax.swing.JComboBox<>();
        cpu8 = new javax.swing.JLabel();
        addCpu8 = new javax.swing.JButton();
        cpuPrice8 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();

        cpu1.setText("CPU 1: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        cpuCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpuPrice1.setText("price");

        addCpu1.setText("Add");
        addCpu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu1ActionPerformed(evt);
            }
        });

        cpu2.setText("CPU 2: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        cpuCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpuPrice2.setText("price");

        addCpu2.setText("Add");
        addCpu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu2ActionPerformed(evt);
            }
        });

        cpuPrice3.setText("price");

        addCpu3.setText("Add");
        addCpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu3ActionPerformed(evt);
            }
        });

        cpu3.setText("CPU 3: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        cpuCombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpu4.setText("CPU 4: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        addCpu4.setText("Add");
        addCpu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu4ActionPerformed(evt);
            }
        });

        cpuCombo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpuPrice4.setText("price");

        cpu5.setText("CPU 5: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        addCpu5.setText("Add");
        addCpu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu5ActionPerformed(evt);
            }
        });

        cpuCombo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpuPrice5.setText("price");

        cpu6.setText("CPU 6: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        addCpu6.setText("Add");
        addCpu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu6ActionPerformed(evt);
            }
        });

        cpuPrice6.setText("price");

        cpuCombo6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpu7.setText("CPU 7: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        cpuPrice7.setText("price");

        cpuCombo7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        addCpu7.setText("Add");
        addCpu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu7ActionPerformed(evt);
            }
        });

        cpuCombo8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cpu8.setText("CPU 8: Intel i7 6500U, 4GB dedicated RAM, integraded graphics 520");

        addCpu8.setText("Add");
        addCpu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpu8ActionPerformed(evt);
            }
        });

        cpuPrice8.setText("price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu7, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu8, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCpu4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCpu8))
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCpu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu1ActionPerformed
        // TODO add your handling code here:
        int amount = cpuCombo1.getSelectedIndex();
        OrderSystem.addToShoppingBag(amount, categoryNumber, 1);
    }//GEN-LAST:event_addCpu1ActionPerformed

    private void addCpu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu2ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(1);
        }
    }//GEN-LAST:event_addCpu2ActionPerformed

    private void addCpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu3ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(2);
        }
    }//GEN-LAST:event_addCpu3ActionPerformed

    private void addCpu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu4ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(3);
        }
    }//GEN-LAST:event_addCpu4ActionPerformed

    private void addCpu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu5ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            // osc.addToShoppingBag(4);
        }
    }//GEN-LAST:event_addCpu5ActionPerformed

    private void addCpu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu6ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(5);
        }
    }//GEN-LAST:event_addCpu6ActionPerformed

    private void addCpu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu7ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(6);
        }
    }//GEN-LAST:event_addCpu7ActionPerformed

    private void addCpu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpu8ActionPerformed
        int amount = cpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(7);
        }
    }//GEN-LAST:event_addCpu8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCpu1;
    private javax.swing.JButton addCpu2;
    private javax.swing.JButton addCpu3;
    private javax.swing.JButton addCpu4;
    private javax.swing.JButton addCpu5;
    private javax.swing.JButton addCpu6;
    private javax.swing.JButton addCpu7;
    private javax.swing.JButton addCpu8;
    private javax.swing.JLabel cpu1;
    private javax.swing.JLabel cpu2;
    private javax.swing.JLabel cpu3;
    private javax.swing.JLabel cpu4;
    private javax.swing.JLabel cpu5;
    private javax.swing.JLabel cpu6;
    private javax.swing.JLabel cpu7;
    private javax.swing.JLabel cpu8;
    private javax.swing.JComboBox<String> cpuCombo1;
    private javax.swing.JComboBox<String> cpuCombo2;
    private javax.swing.JComboBox<String> cpuCombo3;
    private javax.swing.JComboBox<String> cpuCombo4;
    private javax.swing.JComboBox<String> cpuCombo5;
    private javax.swing.JComboBox<String> cpuCombo6;
    private javax.swing.JComboBox<String> cpuCombo7;
    private javax.swing.JComboBox<String> cpuCombo8;
    private javax.swing.JLabel cpuPrice1;
    private javax.swing.JLabel cpuPrice2;
    private javax.swing.JLabel cpuPrice3;
    private javax.swing.JLabel cpuPrice4;
    private javax.swing.JLabel cpuPrice5;
    private javax.swing.JLabel cpuPrice6;
    private javax.swing.JLabel cpuPrice7;
    private javax.swing.JLabel cpuPrice8;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
