/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

/**
 *
 * @author Triblex95
 */
public class DesktopPanel extends javax.swing.JPanel {

    /**
     * Creates new form DesktopPanel
     */
    public DesktopPanel() {
        initComponents();
       /*
        desktop1.setText(osc.CPUs.get(0).name);
        desktopPrice1.setText(Integer.toString(osc.CPUs.get(0).price));
        desktop2.setText(osc.CPUs.get(1).name);
        desktopPrice2.setText(Integer.toString(osc.CPUs.get(1).price));
        desktop3.setText(osc.CPUs.get(2).name);
        desktopPrice3.setText(Integer.toString(osc.CPUs.get(2).price));
        desktop4.setText(osc.CPUs.get(3).name);
        desktopPrice4.setText(Integer.toString(osc.CPUs.get(3).price));
        desktop5.setText(osc.CPUs.get(4).name);
        desktopPrice5.setText(Integer.toString(osc.CPUs.get(4).price));
        desktop6.setText(osc.CPUs.get(5).name);
        desktopPrice6.setText(Integer.toString(osc.CPUs.get(5).price));
        desktop7.setText(osc.CPUs.get(6).name);
        desktopPrice7.setText(Integer.toString(osc.CPUs.get(6).price));
        desktop8.setText(osc.CPUs.get(7).name);
        desktopPrice8.setText(Integer.toString(osc.CPUs.get(7).price));
        */
       
    }
        OrderSystemPanel ejer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop1 = new javax.swing.JLabel();
        desktopCombo1 = new javax.swing.JComboBox<>();
        desktopPrice1 = new javax.swing.JLabel();
        addDesktop1 = new javax.swing.JButton();
        addDesktop2 = new javax.swing.JButton();
        desktop2 = new javax.swing.JLabel();
        desktopCombo2 = new javax.swing.JComboBox<>();
        desktopPrice2 = new javax.swing.JLabel();
        desktopPrice3 = new javax.swing.JLabel();
        desktop3 = new javax.swing.JLabel();
        addDesktop3 = new javax.swing.JButton();
        desktopCombo3 = new javax.swing.JComboBox<>();
        desktopPrice4 = new javax.swing.JLabel();
        desktop4 = new javax.swing.JLabel();
        addDesktop4 = new javax.swing.JButton();
        desktopCombo4 = new javax.swing.JComboBox<>();
        desktopCombo5 = new javax.swing.JComboBox<>();
        desktop5 = new javax.swing.JLabel();
        addDesktop5 = new javax.swing.JButton();
        desktopPrice5 = new javax.swing.JLabel();
        desktopCombo6 = new javax.swing.JComboBox<>();
        desktop6 = new javax.swing.JLabel();
        addDesktop6 = new javax.swing.JButton();
        desktopPrice6 = new javax.swing.JLabel();
        desktopPrice7 = new javax.swing.JLabel();
        addDesktop7 = new javax.swing.JButton();
        desktopCombo7 = new javax.swing.JComboBox<>();
        desktop7 = new javax.swing.JLabel();
        desktop8 = new javax.swing.JLabel();
        desktopPrice8 = new javax.swing.JLabel();
        desktopCombo8 = new javax.swing.JComboBox<>();
        addDesktop8 = new javax.swing.JButton();

        desktop1.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        desktopCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktopPrice1.setText("price");

        addDesktop1.setText("Add");
        addDesktop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop1ActionPerformed(evt);
            }
        });

        addDesktop2.setText("Add");
        addDesktop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop2ActionPerformed(evt);
            }
        });

        desktop2.setText("sad");

        desktopCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktopPrice2.setText("price");

        desktopPrice3.setText("price");

        desktop3.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addDesktop3.setText("Add");
        addDesktop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop3ActionPerformed(evt);
            }
        });

        desktopCombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktopPrice4.setText("price");

        desktop4.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addDesktop4.setText("Add");
        addDesktop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop4ActionPerformed(evt);
            }
        });

        desktopCombo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktopCombo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktop5.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addDesktop5.setText("Add");
        addDesktop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop5ActionPerformed(evt);
            }
        });

        desktopPrice5.setText("price");

        desktopCombo6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktop6.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addDesktop6.setText("Add");
        addDesktop6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop6ActionPerformed(evt);
            }
        });

        desktopPrice6.setText("price");

        desktopPrice7.setText("price");

        addDesktop7.setText("Add");
        addDesktop7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop7ActionPerformed(evt);
            }
        });

        desktopCombo7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        desktop7.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        desktop8.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        desktopPrice8.setText("price");

        desktopCombo8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        addDesktop8.setText("Add");
        addDesktop8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktop8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop7, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop8, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDesktop8)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktop8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDesktop8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDesktop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop1ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }
    }//GEN-LAST:event_addDesktop1ActionPerformed

    private void addDesktop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop2ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
           // osc.addToShoppingBag(1);
        }
    }//GEN-LAST:event_addDesktop2ActionPerformed

    private void addDesktop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop3ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(2);
        }
    }//GEN-LAST:event_addDesktop3ActionPerformed

    private void addDesktop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop4ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(3);
        }
    }//GEN-LAST:event_addDesktop4ActionPerformed

    private void addDesktop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop5ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(4);
        }
    }//GEN-LAST:event_addDesktop5ActionPerformed

    private void addDesktop6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop6ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(5);
        }
    }//GEN-LAST:event_addDesktop6ActionPerformed

    private void addDesktop7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop7ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(6);
        }
    }//GEN-LAST:event_addDesktop7ActionPerformed

    private void addDesktop8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktop8ActionPerformed
        // TODO add your handling code here:
        int amount = desktopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(7);
        }
    }//GEN-LAST:event_addDesktop8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDesktop1;
    private javax.swing.JButton addDesktop2;
    private javax.swing.JButton addDesktop3;
    private javax.swing.JButton addDesktop4;
    private javax.swing.JButton addDesktop5;
    private javax.swing.JButton addDesktop6;
    private javax.swing.JButton addDesktop7;
    private javax.swing.JButton addDesktop8;
    private javax.swing.JLabel desktop1;
    private javax.swing.JLabel desktop2;
    private javax.swing.JLabel desktop3;
    private javax.swing.JLabel desktop4;
    private javax.swing.JLabel desktop5;
    private javax.swing.JLabel desktop6;
    private javax.swing.JLabel desktop7;
    private javax.swing.JLabel desktop8;
    private javax.swing.JComboBox<String> desktopCombo1;
    private javax.swing.JComboBox<String> desktopCombo2;
    private javax.swing.JComboBox<String> desktopCombo3;
    private javax.swing.JComboBox<String> desktopCombo4;
    private javax.swing.JComboBox<String> desktopCombo5;
    private javax.swing.JComboBox<String> desktopCombo6;
    private javax.swing.JComboBox<String> desktopCombo7;
    private javax.swing.JComboBox<String> desktopCombo8;
    private javax.swing.JLabel desktopPrice1;
    private javax.swing.JLabel desktopPrice2;
    private javax.swing.JLabel desktopPrice3;
    private javax.swing.JLabel desktopPrice4;
    private javax.swing.JLabel desktopPrice5;
    private javax.swing.JLabel desktopPrice6;
    private javax.swing.JLabel desktopPrice7;
    private javax.swing.JLabel desktopPrice8;
    // End of variables declaration//GEN-END:variables
}
