/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

/**
 *
 * @author Triblex95
 */
public class GPUPanel extends javax.swing.JPanel {

    OrderSystemPanel ejer;

    /**
     * Creates new form GPUPanel
     */
    public GPUPanel() {
        initComponents();
        /*
        gpu1.setText(osc.CPUs.get(0).name);
        gpuPrice1.setText(Integer.toString(osc.CPUs.get(0).price));
        gpu2.setText(osc.CPUs.get(1).name);
        gpuPrice2.setText(Integer.toString(osc.CPUs.get(1).price));
        gpu3.setText(osc.CPUs.get(2).name);
        gpuPrice3.setText(Integer.toString(osc.CPUs.get(2).price));
        gpu4.setText(osc.CPUs.get(3).name);
        gpuPrice4.setText(Integer.toString(osc.CPUs.get(3).price));
        gpu5.setText(osc.CPUs.get(4).name);
        gpuPrice5.setText(Integer.toString(osc.CPUs.get(4).price));
        gpu6.setText(osc.CPUs.get(5).name);
        gpuPrice6.setText(Integer.toString(osc.CPUs.get(5).price));
        gpu7.setText(osc.CPUs.get(6).name);
        gpuPrice7.setText(Integer.toString(osc.CPUs.get(6).price));
        gpu8.setText(osc.CPUs.get(7).name);
        gpuPrice8.setText(Integer.toString(osc.CPUs.get(7).price));
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpu1 = new javax.swing.JLabel();
        gpuCombo1 = new javax.swing.JComboBox<String>();
        gpuPrice1 = new javax.swing.JLabel();
        addGpu1 = new javax.swing.JButton();
        gpuPrice2 = new javax.swing.JLabel();
        addGpu2 = new javax.swing.JButton();
        gpu2 = new javax.swing.JLabel();
        gpuCombo2 = new javax.swing.JComboBox<String>();
        addGpu3 = new javax.swing.JButton();
        gpuCombo3 = new javax.swing.JComboBox<String>();
        gpuPrice3 = new javax.swing.JLabel();
        gpu3 = new javax.swing.JLabel();
        addGpu4 = new javax.swing.JButton();
        gpu4 = new javax.swing.JLabel();
        gpuPrice4 = new javax.swing.JLabel();
        gpuCombo4 = new javax.swing.JComboBox<String>();
        gpu5 = new javax.swing.JLabel();
        gpuCombo5 = new javax.swing.JComboBox<String>();
        gpuPrice5 = new javax.swing.JLabel();
        addGpu5 = new javax.swing.JButton();
        addGpu6 = new javax.swing.JButton();
        gpuCombo6 = new javax.swing.JComboBox<String>();
        gpuPrice6 = new javax.swing.JLabel();
        gpu6 = new javax.swing.JLabel();
        gpuCombo7 = new javax.swing.JComboBox<String>();
        addGpu7 = new javax.swing.JButton();
        gpuPrice7 = new javax.swing.JLabel();
        gpu7 = new javax.swing.JLabel();
        gpuCombo8 = new javax.swing.JComboBox<String>();
        gpuPrice8 = new javax.swing.JLabel();
        gpu8 = new javax.swing.JLabel();
        addGpu8 = new javax.swing.JButton();

        gpu1.setText("GPU 1: GForce GTX 990x 8GB");

        gpuCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        gpuPrice1.setText("price");

        addGpu1.setText("Add");
        addGpu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu1ActionPerformed(evt);
            }
        });

        gpuPrice2.setText("price");

        addGpu2.setText("Add");
        addGpu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu2ActionPerformed(evt);
            }
        });

        gpu2.setText("GPU 2: GForce GTX 990x 8GB");

        gpuCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        addGpu3.setText("Add");
        addGpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu3ActionPerformed(evt);
            }
        });

        gpuCombo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        gpuPrice3.setText("price");

        gpu3.setText("GPU 3: GForce GTX 990x 8GB");

        addGpu4.setText("Add");
        addGpu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu4ActionPerformed(evt);
            }
        });

        gpu4.setText("GPU 4: GForce GTX 990x 8GB");

        gpuPrice4.setText("price");

        gpuCombo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        gpu5.setText("GPU 5: GForce GTX 990x 8GB");

        gpuCombo5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        gpuPrice5.setText("price");

        addGpu5.setText("Add");
        addGpu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu5ActionPerformed(evt);
            }
        });

        addGpu6.setText("Add");
        addGpu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu6ActionPerformed(evt);
            }
        });

        gpuCombo6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        gpuPrice6.setText("price");

        gpu6.setText("GPU 6: GForce GTX 990x 8GB");

        gpuCombo7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        addGpu7.setText("Add");
        addGpu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu7ActionPerformed(evt);
            }
        });

        gpuPrice7.setText("price");

        gpu7.setText("GPU 7: GForce GTX 990x 8GB");

        gpuCombo8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        gpuPrice8.setText("price");

        gpu8.setText("GPU 8: GForce GTX 990x 8GB");

        addGpu8.setText("Add");
        addGpu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGpu8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu7, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gpu8, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpuPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGpu8)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpu8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpuPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGpu8))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addGpu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu1ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu1ActionPerformed

    private void addGpu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu2ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //sc.addToShoppingBag(1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu2ActionPerformed

    private void addGpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu3ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(2);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu3ActionPerformed

    private void addGpu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu4ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(3);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu4ActionPerformed

    private void addGpu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu5ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
           //osc.addToShoppingBag(4);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu5ActionPerformed

    private void addGpu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu6ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(5);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu6ActionPerformed

    private void addGpu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu7ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(6);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu7ActionPerformed

    private void addGpu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGpu8ActionPerformed
        int amount = gpuCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(7);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addGpu8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGpu1;
    private javax.swing.JButton addGpu2;
    private javax.swing.JButton addGpu3;
    private javax.swing.JButton addGpu4;
    private javax.swing.JButton addGpu5;
    private javax.swing.JButton addGpu6;
    private javax.swing.JButton addGpu7;
    private javax.swing.JButton addGpu8;
    private javax.swing.JLabel gpu1;
    private javax.swing.JLabel gpu2;
    private javax.swing.JLabel gpu3;
    private javax.swing.JLabel gpu4;
    private javax.swing.JLabel gpu5;
    private javax.swing.JLabel gpu6;
    private javax.swing.JLabel gpu7;
    private javax.swing.JLabel gpu8;
    private javax.swing.JComboBox<String> gpuCombo1;
    private javax.swing.JComboBox<String> gpuCombo2;
    private javax.swing.JComboBox<String> gpuCombo3;
    private javax.swing.JComboBox<String> gpuCombo4;
    private javax.swing.JComboBox<String> gpuCombo5;
    private javax.swing.JComboBox<String> gpuCombo6;
    private javax.swing.JComboBox<String> gpuCombo7;
    private javax.swing.JComboBox<String> gpuCombo8;
    private javax.swing.JLabel gpuPrice1;
    private javax.swing.JLabel gpuPrice2;
    private javax.swing.JLabel gpuPrice3;
    private javax.swing.JLabel gpuPrice4;
    private javax.swing.JLabel gpuPrice5;
    private javax.swing.JLabel gpuPrice6;
    private javax.swing.JLabel gpuPrice7;
    private javax.swing.JLabel gpuPrice8;
    // End of variables declaration//GEN-END:variables
}
