/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

/**
 *
 * @author Triblex95
 */
public class LaptopsPanel extends javax.swing.JPanel {

    OrderSystemPanel ejer;

    /**
     * Creates new form Laptops
     */
    public LaptopsPanel() {
        initComponents();
        /*
        laptop1.setText(osc.CPUs.get(0).name);
        laptopPrice1.setText(Integer.toString(osc.CPUs.get(0).price));
        laptop2.setText(osc.CPUs.get(1).name);
        laptopPrice2.setText(Integer.toString(osc.CPUs.get(1).price));
        laptop3.setText(osc.CPUs.get(2).name);
        laptopPrice3.setText(Integer.toString(osc.CPUs.get(2).price));
        laptop4.setText(osc.CPUs.get(3).name);
        laptopPrice4.setText(Integer.toString(osc.CPUs.get(3).price));
        laptop5.setText(osc.CPUs.get(4).name);
        laptopPrice5.setText(Integer.toString(osc.CPUs.get(4).price));
        laptop6.setText(osc.CPUs.get(5).name);
        laptopPrice6.setText(Integer.toString(osc.CPUs.get(5).price));
        laptop7.setText(osc.CPUs.get(6).name);
        laptopPrice7.setText(Integer.toString(osc.CPUs.get(6).price));
        laptop8.setText(osc.CPUs.get(7).name);
        laptopPrice8.setText(Integer.toString(osc.CPUs.get(7).price));
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laptop1 = new javax.swing.JLabel();
        laptopCombo1 = new javax.swing.JComboBox<String>();
        laptopPrice1 = new javax.swing.JLabel();
        addLaptop1 = new javax.swing.JButton();
        laptop2 = new javax.swing.JLabel();
        addLaptop2 = new javax.swing.JButton();
        laptopCombo2 = new javax.swing.JComboBox<String>();
        laptopPrice2 = new javax.swing.JLabel();
        laptop3 = new javax.swing.JLabel();
        addLaptop3 = new javax.swing.JButton();
        laptopCombo3 = new javax.swing.JComboBox<String>();
        laptopPrice3 = new javax.swing.JLabel();
        laptopPrice4 = new javax.swing.JLabel();
        laptop4 = new javax.swing.JLabel();
        addLaptop4 = new javax.swing.JButton();
        laptopCombo4 = new javax.swing.JComboBox<String>();
        laptopPrice5 = new javax.swing.JLabel();
        laptopCombo5 = new javax.swing.JComboBox<String>();
        laptop5 = new javax.swing.JLabel();
        addLaptop5 = new javax.swing.JButton();
        laptop6 = new javax.swing.JLabel();
        laptopPrice6 = new javax.swing.JLabel();
        addLaptop6 = new javax.swing.JButton();
        laptopCombo6 = new javax.swing.JComboBox<String>();
        laptop7 = new javax.swing.JLabel();
        laptopPrice7 = new javax.swing.JLabel();
        addLaptop7 = new javax.swing.JButton();
        laptopCombo7 = new javax.swing.JComboBox<String>();
        laptop8 = new javax.swing.JLabel();
        laptopPrice8 = new javax.swing.JLabel();
        addLaptop8 = new javax.swing.JButton();
        laptopCombo8 = new javax.swing.JComboBox<String>();

        laptop1.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        laptopCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptopPrice1.setText("price");

        addLaptop1.setText("Add");
        addLaptop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop1ActionPerformed(evt);
            }
        });

        laptop2.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addLaptop2.setText("Add");
        addLaptop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop2ActionPerformed(evt);
            }
        });

        laptopCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptopPrice2.setText("price");

        laptop3.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addLaptop3.setText("Add");
        addLaptop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop3ActionPerformed(evt);
            }
        });

        laptopCombo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptopPrice3.setText("price");

        laptopPrice4.setText("price");

        laptop4.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addLaptop4.setText("Add");
        addLaptop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop4ActionPerformed(evt);
            }
        });

        laptopCombo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptopPrice5.setText("price");

        laptopCombo5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptop5.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        addLaptop5.setText("Add");
        addLaptop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop5ActionPerformed(evt);
            }
        });

        laptop6.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        laptopPrice6.setText("price");

        addLaptop6.setText("Add");
        addLaptop6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop6ActionPerformed(evt);
            }
        });

        laptopCombo6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptop7.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        laptopPrice7.setText("price");

        addLaptop7.setText("Add");
        addLaptop7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop7ActionPerformed(evt);
            }
        });

        laptopCombo7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        laptop8.setText("Laptop 1: 256 SSD, Intel i7 6500U processor, Intel integrated graphics 520, full HD 1080p screen.");

        laptopPrice8.setText("price");

        addLaptop8.setText("Add");
        addLaptop8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaptop8ActionPerformed(evt);
            }
        });

        laptopCombo8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laptop7, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laptopCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laptopPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLaptop7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(laptop1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laptopCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laptopPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laptop2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laptop6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laptop5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laptop4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laptop3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(laptopPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addLaptop2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addLaptop3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addLaptop4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addLaptop5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addLaptop6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(addLaptop1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laptop8, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laptopCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laptopPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLaptop8)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptop8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopCombo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laptopPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLaptop8))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLaptop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop1ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop1ActionPerformed

    private void addLaptop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop2ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop2ActionPerformed

    private void addLaptop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop3ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop3ActionPerformed

    private void addLaptop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop4ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop4ActionPerformed

    private void addLaptop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop5ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop5ActionPerformed

    private void addLaptop6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop6ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop6ActionPerformed

    private void addLaptop7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop7ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop7ActionPerformed

    private void addLaptop8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaptop8ActionPerformed
        int amount = laptopCombo1.getSelectedIndex();
        for (int i = 0; i <= amount; i++) {
            //osc.addToShoppingBag(0);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addLaptop8ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLaptop1;
    private javax.swing.JButton addLaptop2;
    private javax.swing.JButton addLaptop3;
    private javax.swing.JButton addLaptop4;
    private javax.swing.JButton addLaptop5;
    private javax.swing.JButton addLaptop6;
    private javax.swing.JButton addLaptop7;
    private javax.swing.JButton addLaptop8;
    private javax.swing.JLabel laptop1;
    private javax.swing.JLabel laptop2;
    private javax.swing.JLabel laptop3;
    private javax.swing.JLabel laptop4;
    private javax.swing.JLabel laptop5;
    private javax.swing.JLabel laptop6;
    private javax.swing.JLabel laptop7;
    private javax.swing.JLabel laptop8;
    private javax.swing.JComboBox<String> laptopCombo1;
    private javax.swing.JComboBox<String> laptopCombo2;
    private javax.swing.JComboBox<String> laptopCombo3;
    private javax.swing.JComboBox<String> laptopCombo4;
    private javax.swing.JComboBox<String> laptopCombo5;
    private javax.swing.JComboBox<String> laptopCombo6;
    private javax.swing.JComboBox<String> laptopCombo7;
    private javax.swing.JComboBox<String> laptopCombo8;
    private javax.swing.JLabel laptopPrice1;
    private javax.swing.JLabel laptopPrice2;
    private javax.swing.JLabel laptopPrice3;
    private javax.swing.JLabel laptopPrice4;
    private javax.swing.JLabel laptopPrice5;
    private javax.swing.JLabel laptopPrice6;
    private javax.swing.JLabel laptopPrice7;
    private javax.swing.JLabel laptopPrice8;
    // End of variables declaration//GEN-END:variables

}
