/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;

/**
 *
 * @author Triblex95
 */
public class OrderSystemPanel extends javax.swing.JPanel {

    OrderSystem osc = new OrderSystem();

    /**
     * Creates new form bestillingsSystemPanel
     */

    
    public OrderSystemPanel() {
        initComponents();
        checkoutPanel1.ejer = this;
        shoppingBagPanel1.ejer = this;
        userProfilePanel1.ejer = this;
        support1.ejer = this;
        CPUPanel.ejer = this;
        
        
        LoggedInAs.setVisible(false);
        loggedInUsername.setVisible(false);
        logOut.setVisible(false);
        //tabbedPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        LoggedInAs = new javax.swing.JLabel();
        loggedInUsername = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        sSDPanel1 = new ordersystem.SSDPanel();
        laptopsPanel1 = new ordersystem.LaptopsPanel();
        gPUPanel1 = new ordersystem.GPUPanel();
        desktopPanel1 = new ordersystem.DesktopPanel();
        checkoutPanel1 = new ordersystem.CheckoutPanel();
        userProfilePanel1 = new ordersystem.UserProfilePanel();
        support1 = new ordersystem.Support();
        shoppingBagPanel1 = new ordersystem.ShoppingBagPanel();

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        logIn.setText("Log in");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });

        jLabel4.setText("Welcome to MusMic co. ordering system!");

        LoggedInAs.setText("Logged in as:");

        loggedInUsername.setText("loginName");

        logOut.setText("Log out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        jTabbedPane4.addTab("SSD", sSDPanel1);
        jTabbedPane4.addTab("Laptops", laptopsPanel1);
        jTabbedPane4.addTab("GPUs", gPUPanel1);
        jTabbedPane4.addTab("Desktops", desktopPanel1);

        jTabbedPane1.addTab("Items", jTabbedPane4);
        jTabbedPane1.addTab("Checkout", checkoutPanel1);
        jTabbedPane1.addTab("Profile", userProfilePanel1);
        jTabbedPane1.addTab("Support", support1);
        jTabbedPane1.addTab("Shopping bag", shoppingBagPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logIn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoggedInAs, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loggedInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOut)
                        .addGap(27, 27, 27))))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password)
                            .addComponent(userName)
                            .addComponent(LoggedInAs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loggedInUsername)
                            .addComponent(logOut)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        // TODO add your handling code here:
        String un = userName.getText();
        int pw = Integer.parseInt(password.getText());
        if (OrderSystem.logIn(un, pw)) {
            loggedInUsername.setText(OrderSystem.Users.get(OrderSystem.userIndex).userName);
            LoggedInAs.setVisible(true);
            loggedInUsername.setVisible(true);
            logOut.setVisible(true);
            logIn.setVisible(false);
            
            //tabbedPanel.setVisible(true);
        }
    }//GEN-LAST:event_logInActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        LoggedInAs.setVisible(false);
        loggedInUsername.setVisible(false);
        loggedInUsername.setText("Nobody");
        logOut.setVisible(false);
        logIn.setVisible(true);
        osc.adminMode = false;
        osc.userMode = false;
        
    }//GEN-LAST:event_logOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoggedInAs;
    private ordersystem.CheckoutPanel checkoutPanel1;
    private ordersystem.DesktopPanel desktopPanel1;
    private ordersystem.GPUPanel gPUPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private ordersystem.LaptopsPanel laptopsPanel1;
    private javax.swing.JButton logIn;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel loggedInUsername;
    private javax.swing.JPasswordField password;
    private ordersystem.SSDPanel sSDPanel1;
    private ordersystem.ShoppingBagPanel shoppingBagPanel1;
    private ordersystem.Support support1;
    private javax.swing.JTextField userName;
    private ordersystem.UserProfilePanel userProfilePanel1;
    // End of variables declaration//GEN-END:variables
}
